Simple workaround to avoid CI test failure.
```
org.testcontainers.junit.DockerComposeContainerWithBuildTest > performTest[removeMode = ALL] FAILED
    java.lang.RuntimeException: java.lang.AssertionError: the pulled image is present after running: 'true' does not equal expected 'false'
        at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
        at org.rnorth.ducttape.timeouts.Timeouts.getWithTimeout(Timeouts.java:43)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:40)
        at org.testcontainers.junit.DockerComposeContainerWithBuildTest.performTest(DockerComposeContainerWithBuildTest.java:72)

        Caused by:
        java.lang.AssertionError: the pulled image is present after running: 'true' does not equal expected 'false'
            at org.rnorth.visibleassertions.VisibleAssertions.fail(VisibleAssertions.java:440)
            at org.rnorth.visibleassertions.VisibleAssertions.assertEquals(VisibleAssertions.java:174)
            at org.testcontainers.junit.DockerComposeContainerWithBuildTest.lambda$performTest$1(DockerComposeContainerWithBuildTest.java:74)
```

Hypothesis: docker-compose cannot remove the `redis` (latest) image because there is some other running container that relies on that image. This may be a CI-specific problem depending on the Azure Pipelines Docker setup.

To work around (without publishing our own single-use image): use an old version of the Redis image that is unlikely to be in use by concurrent builds.