Fix random test failure by removing dependency on Alpine package server. (#505)
* Fix random test failure by removing dependency on Alpine package server.

This fixes an occasional random failure during docker image build,
seemingly due to a failure to download alpine package indices:
```
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.3/main: temporary error (try again later)
...
ERROR 🐳 [testcontainers/cbwpthsp79aee52s] - The command '/bin/sh -c apk add --update nginx' returned a non-zero code: 1
```